### ISSUE TITLE
Button's on Blast Furnace

### ISSUE THREAD

**Issue by phDoenix** [FabianMPunkt/Nautilus3D#1]
Buttons placed on Blast Furnaces have a slight texture bleeding/flashing issue. I'm sure this issue is present on other objects because of the 3D modeling approach
![2022-01-07_13 33 22](https://user-images.githubusercontent.com/93850160/148610725-f43b9757-fbb3-42fe-aedb-01bc29a50c0a.png)
.

**Comment by TheWaschtlPlays** [comment]
Thanks for reporting this! I've never really checked if this occurs on any blocks besides obvious redstone-related blocks.
I'll see if i can re-design the furnace slightly or something.

**Comment by FabianMPunkt** [comment]
It's been a while but i finally fixed it :)

it'll be in the next update

![image](https://user-images.githubusercontent.com/78741736/180620597-74411d85-2540-41d3-ab85-75df4ef12972.png)
