### ISSUE TITLE
The vanilla texture of nether portal is still visible when breaking a nether portal

### ISSUE THREAD

**Issue by AagneyS** [FabianMPunkt/Nautilus3D#11]
### Game Version

fabric loader 0.15.3 (1.20.4)

### List all installed mods

![modsefajfiafh](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/ef693f9f-09d8-4a7c-8f99-8dac645ba4b5)

### List of all loaded packs

Nautilus3D V1.9.1 ,  Default resource pack.

### Describe your issue

![2023-12-27_10 46 14](https://github.com/FabianMPunkt/Nautilus3D/assets/152633374/5e1fe4a2-407f-440e-9785-846c9bf62f22)

**Comment by AagneyS** [comment]
When breaking a nether portal for a slight moment you can see the vanilla textures appearing.

**Comment by FabianMPunkt** [comment]
Hey, thanks for reporting.
Not sure why it doesn't show the ctm-textures in the split-second when breaking the portal, but i added the center-ctm-texture as the default nether_portal.png. This way it is a lot less visible.
35250a402265c124ec90355272a0bd4d2cfe5f04
