### ISSUE TITLE
no texture under the torch on fences

### ISSUE THREAD

**Issue by Kukidoo** [FabianMPunkt/Nautilus3D#13]
### Game Version

fabric-loader-0.15.7-1.20.1

### List all installed mods

        - additionalstructures 4.2.1
	- advanced_runtime_resource_pack 0.8.1
	- advancementinfo 1.20-fabric0.83.0-1.4
	- ambientsounds 5.3.9
	- animatica 0.6+1.20
	- antighost 1.20-fabric0.83.0-1.1.5
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- auto_third_person 2.1
	- beaconoverhaul 1.8.4+1.20
	- betterf3 7.0.2
	- bettermounthud 1.2.2
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.9.0
	- bookshelf 20.1.9
	- borderlessmining 1.1.8+1.20.1
	- bundle_jumble 1.0.2-mc1.20.1
	- bushierflowers 0.0.3-1.20.1
	- c2me 0.2.0+alpha.11.5
	- carryon 2.1.2.7
	- cavedust 1.4.1
	- chat_heads 0.10.31
	- chatanimation 1.0.5
	- chunksfadein 1.0.5-1.20.1
	- citresewn 1.1.3+1.20
	- cloth-config 11.1.118
	- clumps 12.0.0.3
	- companion 5.1.0
	- continuity 3.0.0-beta.4+1.20.1
	- controlling 12.0.2
	- creativecore 2.11.24
	- debugify 1.20.1+2.0
	- disable_custom_worlds_advice 4.1
	- dynamic_fps 3.4.2
	- dynamiccrosshair 7.4.4+1.20
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.2
	- eatinganimationid 1.20+1.9.5
	- elytra_physics 1.3-1.20
	- emojitype 2.2.3+1.20.4
	- enhancedblockentities 0.9+1.20
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2-mc1.20.1
	- essential-container 1.0.0
	- fabric-api 0.92.0+1.20.1
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	- fabricloader 0.15.7
	- fabricskyboxes 0.7.3+mc1.20.1
	- fabrishot 1.10.1
	- fallingleaves 1.15.4
	- fastipping 1.0.1
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- fsb-interop 1.3.6+mc1.20.1-build.50
	- holdthatchunk 2.0.1
	- iceberg 1.1.18
	- immediatelyfast 1.2.10+1.20.4
	- indium 1.0.30+mc1.20.4
	- inventorysorter 1.9.0-1.20
	- iris 1.6.17
	- isxander-main-menu-credits 1.1.2
	- itemphysic 1.7.0
	- java 17
	- kiwi 11.5.5
	- lambdynlights 2.3.2+1.20.1
	- languagereload 1.5.10+1.20.1
	- lazydfu 0.1.3
	- leavesbegone 8.0.0
	- legendarytooltips 1.4.4
	- lilac 1.0.0-beta.3
	- lithium 0.11.2
	- make_bubbles_pop 0.2.0-fabric
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- modelfix 1.14
	- modmenu 7.2.2
	- morechathistory 1.3.0
	- moreculling 1.20.4-0.22.1
	- moremobvariants 1.2.2
	- mousetweaks 2.25
	- nimble 5.0.1
	- no-resource-pack-warnings 1.3.0
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.1
	- nvidium 0.2.6-beta
	- nyfsspiders 2.1.1
	- optigui 2.1.7
	- oscimate_soulflame 1.1.0
	- physicsmod 3.0.13
	- pickupnotifier 8.0.0
	- presencefootsteps 1.9.1
	- prism 1.0.5
	- puzzle 1.5.2+1.20
	- puzzleslib 8.1.17
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefullib 2.1.23
	- rrls 3.2.0-1.20.1-fabric
	- searchables 1.0.1
	- shouldersurfing 2.5
	- skinlayers3d 1.6.2
	- sleepwarp 2.2.0_rc1+1.20.1
	- slight-gui-modifications 2.6.1
	- smoothswapping 0.9.3.1
	- snowrealmagic 10.3.1
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	- sound_physics_remastered 1.20.1-1.1.2
	- starlight 1.1.2+fabric.dbc156f
	- structory 1.3.2
	- tia 1.20-1.1
	- vcinteraction 1.20.1-1.0.6
	- visuality 0.7.1+1.20
	- visualworkbench 8.0.0
	- voicechat 1.20.1-2.5.7
	- wakes 0.2.0
	- yosbr 0.1.2
	- zoomify 2.11.2

### List of all loaded packs

only Nautilus3D-V1.9.1

### Describe your issue

no fence texture if torch placed on top of fence
![image_2024-03-07_14-11-47](https://github.com/FabianMPunkt/Nautilus3D/assets/48352159/aa835d2a-388b-458b-bb7e-bc72df5d9fa3)

**Comment by FabianMPunkt** [comment]
This is caused by the "More Culling" mod. Looks like it has hardcoded names for the fence models and stuff so it doesn't apply correctly with Nautilus3D. You can either remove the mod entirely, or disable "BlockState culling" in the mod's settings.

**Comment by Kukidoo** [comment]
Yes, it really worked. Thank you so much!
