### ISSUE TITLE
Bushy leaves are not working on 1.20.4

### ISSUE THREAD

**Issue by Mattipotaatti** [FabianMPunkt/Nautilus3D#14]
### Game Version

Optifine 1.20.4

### List all installed mods

Just Optifine

### List of all loaded packs

Nautilus 3D
Fresh Animations
Fancy Beds

### Describe your issue

When i put the Texture pack On The leaves are not bushy they are glitching

**Comment by Mattipotaatti** [comment]
Got it Working No Worries

**Comment by FabianMPunkt** [comment]
Ok great!
