### ISSUE TITLE
Blocks are dark 

### ISSUE THREAD

**Issue by PosTerxc** [FabianMPunkt/Nautilus3D#19]
### Game Version

fabric-loader-0.15.11-1.18.2

### List all installed mods

![Снимок экрана 2024-06-29 145931](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/e26682b2-8012-42fe-a751-b37898f7035a)
![Снимок экрана 2024-06-29 145938](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/4de76d1c-6301-4729-963b-511a3b8d6157)

### List of all loaded packs

![Снимок экрана 2024-06-29 150517](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/c282d100-2c22-4055-b8db-87e5ef325a83)
![Снимок экрана 2024-06-29 150533](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/67f053e5-88a2-41d7-8950-ebecc2b7488b)
![Снимок экрана 2024-06-29 150540](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/8f69452e-ec20-452a-b397-e70a00f74253)
![Снимок экрана 2024-06-29 150605](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/49d19e12-b692-4007-9f9c-f06c538830a5)
![Снимок экрана 2024-06-29 150611](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/4da1089e-386c-41a6-8c6d-317254f53ccb)
![Снимок экрана 2024-06-29 150626](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/b57e2e2d-e5b2-4a5e-b1e8-9c6f6ca7f30f)
![Снимок экрана 2024-06-29 150632](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/80caaf83-1c84-4a4c-beb3-adca6aa86974)

### Describe your issue

I have a problem when i place blocks like crafting table, furnance and bookshelf they are black and i tried without other resourse packs and still the same
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/174192890/f7ff10b1-2fff-44fd-8bae-4c460c47ecf7)

**Comment by FabianMPunkt** [comment]
Hey, this used to be an issue on older sodium versions that has since been fixed (#3)
Not sure if new sodium versions are available for 1.18.2 an such. Why are you even playing on such ancient Minecraft? :D
