### ISSUE TITLE
Cartography Table Issue

### ISSUE THREAD

**Issue by NerdCraftDev** [FabianMPunkt/Nautilus3D#2]
When I place a block by the globe on the cartography table, the part of the block that is exposed because of the globe disappears.
![image](https://user-images.githubusercontent.com/97327678/148632240-b503c5a9-affb-4fc3-a854-6e9032faa34f.png)

**Comment by TheWaschtlPlays** [comment]
Yes i know this is a problem.. unfortunately there isn't really a fix for this because of how cullfaces in Minecraft work.
Only way would be to not make the 3D-model rounded.

**Comment by FabianMPunkt** [comment]
I took the time to fully redesign the cartography table so this is no longer an issue:

![image](https://user-images.githubusercontent.com/78741736/180647266-a3f00415-8db1-4af6-8c4c-90b0e7900456.png)
