### ISSUE TITLE
[Feature request] Chests, trapped chests, minecart chests, chestboats and enderchests retextures 

### ISSUE THREAD

**Issue by AngelayXV** [FabianMPunkt/Nautilus3D#21]
**Is your feature request related to a problem? Please describe.**
No, just a "selfish" request honestly.

**Describe the request you'd like**
Chests, trapped chests, minecart chests, chestboats and enderchests retextures, because the regular ones still use the old textures which look completely different from the *Minecraft* artstyle we have today. 

**Describe alternatives you've considered**
The regular chest types don't need anything fancy. They just need to be easier on the eyes and a little more modernized to the current artstyle. Maybe a slight wood color variation or a bit of redstone around the lock for the trapped chest to be a little more recognizable.

As for the enderchest, same as the regular ones, basically a little more modernized. What I think would be nice additions are some gold accents and the ender eye to pop out a little more. On top of that an end portal texture upon opening would be cool and unique.

These are just some suggestions though.

**Additional context**
Amazing work is always put into this pack :D and that's exactly why I'm requesting it here. It would also be a nice addition considering the other container blocks have proper retextures.

**Comment by FabianMPunkt** [comment]
Here's what i came up with:
Normal chests have a slight re-texture and a modeled interior. Trapped chests are the same just with a red tint. Maybe i'll update that in the future again when i come up with a better idea for that.
![image](https://github.com/user-attachments/assets/40376f4a-af70-42b6-a8a1-a0b1fc65e57d)
The Ender chest has a portal texture inside (sadly not animated) and a little extruded eye on the front.
![image](https://github.com/user-attachments/assets/f32d6949-e7d6-43b2-9e79-2fc5e3568abc)
