### ISSUE TITLE
[Feature Request] Remove the gui textures, its messing with my other gui resource pack.

### ISSUE THREAD

**Issue by Rylvns** [FabianMPunkt/Nautilus3D#22]
in title

**Comment by Rylvns** [comment]
ive tried to do it manually but it broke it

**Comment by Rylvns** [comment]
or just add a setting for this

**Comment by FabianMPunkt** [comment]
If you want to remove the GUI elements just delete the entire `assets/minecraft/textures/gui` folder. Texture packs with settings are not a thing.
