### ISSUE TITLE
[Feature request]Support for Respackopts

### ISSUE THREAD

**Issue by Luna0707** [FabianMPunkt/Nautilus3D#26]
terribly sorry,I am a Taiwanese user,and my English skills are not sufficient for me to state my request,so the following content is translated using Google Translate

Hello Mr. Great Creator, I would like to ask if there is a version without the extra leaves? My computer doesn't allow me to use very good graphics, so my leaves will look very abrupt, but I really, really like the resource pack you made, so I'm making this request to see is there might be a leaf-less version in the future,or the option to turn off leaves?

Thank you for reading and have a nice day
(⁠◍⁠•⁠ᴗ⁠•⁠◍⁠)⁠❤

**Comment by FabianMPunkt** [comment]
Hey, you can remove the leaves by deleting these files:
goto `Nautilus3D/assets/minecraft/blockstates`
search for "leave" and delete all files.
Unfortunately it is not possible to add a settings menu to texture packs, otherwise i would have already done that :c

**Comment by Luna0707** [comment]
I understand, thank you for your help and explanation.
Your texture pack is great, thanks for making it.
Have a nice day♥️

**Comment by OptimusMusmus** [comment]
> Hey, you can remove the leaves by deleting these files: goto `Nautilus3D/assets/minecraft/blockstates` search for "leave" and delete all files. Unfortunately it is not possible to add a settings menu to texture packs, otherwise i would have already done that :c

Wouldn't respackopts be an option? https://modrinth.com/mod/respackopts

**Comment by FabianMPunkt** [comment]
That's a good idea, i didn't know a mod like this existed. I'll look into it, thanks!

**Comment by FabianMPunkt** [comment]
I added some basic settings for Respackops for now. let me know if anything else is needed besides ores and leaves.
(6be306cee48a321fe1e6344a48e395e40507ec24)
