### ISSUE TITLE
Brewing stand showing 2d model and 3d model 

### ISSUE THREAD

**Issue by Kloytz** [FabianMPunkt/Nautilus3D#27]
### Game Version

Fabric loader 0.16.5 on 1.21.1

### List all installed mods

![image](https://github.com/user-attachments/assets/817cc5b8-3bdb-4f7f-a2b7-97885143e84e)
![image](https://github.com/user-attachments/assets/dc3d8086-ee19-4a2f-8799-f1bbca592f4d)
![image](https://github.com/user-attachments/assets/43c8f7a8-311b-4ad2-88b2-91601b94519a)
![image](https://github.com/user-attachments/assets/88a31c22-1e12-46be-a131-d0b7931e02b9)

### List of all loaded packs

![image](https://github.com/user-attachments/assets/8c62860d-5adc-4368-9857-d304d0f1b964)
![image](https://github.com/user-attachments/assets/4d8e6fbb-4b0b-4e6e-a4a3-ac4b52103762)

### Describe your issue

While using the brewing stand, 2 models of potions appear, 1 2d model and 1 3d model.
![2024-09-22_01 05 35](https://github.com/user-attachments/assets/c6402cb1-66a6-4d70-a8d0-8de41f1f6f3a)

**Comment by FabianMPunkt** [comment]
Looks like it displays two brewing-stand models from different resource-packs at the same time. If you have multiple texture packs that have models for the same block, the vanilla game will always prioritize whatever pack is first in the list of all loaded packs. My best quess is that one of your many mods changes how texture packs are loaded.
