### ISSUE TITLE
furnaces

### ISSUE THREAD

**Issue by kitkat498** [FabianMPunkt/Nautilus3D#3]
when any furnace is used the texture messes up
![Screenshot_20220204_194932](https://user-images.githubusercontent.com/78702592/152586000-a0eab002-0184-4a82-9f4f-e48a00707a68.png)

**Comment by TheWaschtlPlays** [comment]
What? never seen anything like this xD

I see you are using some other texture-blending pack. Which one is it exactly? Are you using any mods or shaders?

Also, what game-version are you on?

**Comment by kitkat498** [comment]
im using fabric 1.18.1 sodium and iris

**Comment by KintsugiKitten** [comment]
I am having the same problem. I believe it has more to do with sodium or iris than the texture pack. It could also be indium, as that is required for some types of 3d block rendering in texture packs.

**Comment by FabianMPunkt** [comment]
Sorry for being gone for a while but here i am lol.

So i did some more testing and research about this and I'm afraid to say, that i can't fix this.

Looks like this is an issue with Sodium other people have already found:
https://github.com/CaffeineMC/sodium-fabric/issues/226

I'll leave this issue open for now.

**Comment by FabianMPunkt** [comment]
Update: according to this pull request on the sodium-repo, it has been fixed an will probably be in one of the next sodium updates.

https://github.com/CaffeineMC/sodium-fabric/pull/1375

**Comment by FabianMPunkt** [comment]
Update: This seems to be fixed with Sodium 4.6!
