### ISSUE TITLE
this seems to over write another res packs animation of my nether portal

### ISSUE THREAD

**Issue by user4302** [FabianMPunkt/Nautilus3D#6]
### Pack edition

v1.7 [1.13 +]

### Game Version

paper-1.19.2-296

### List all installed mods

BetterPvP_22.16.2_Forge_1.19.1.jar
BetterThirdPerson-Forge-1.19-1.8.1.jar
DistantHorizons-1.6.9a-1.19.2.jar
DynamicSurroundings-6.0.0.2.jar
ForgeConfigAPIPort-v4.2.5-1.19.2-Fabric.jar
InventoryHud_[1.19.2].forge-3.4.6.jar
Neat-1.19-32.jar
OptiFine-1.19.2_HD_U_I1_pre2.jar
PresenceFootsteps-1.19.2-1.6.2-beta1-forge.jar
cloth-config-8.2.88-fabric.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabric-api-0.62.0+1.19.2.jar
jei-1.19.2-forge-11.4.0.274.jar
justzoom_forge_1.0.1-1_MC_1.19.jar
konkrete_forge_1.5.3_MC_1.19-1.19.2.jar
lithium-fabric-mc1.19.2-0.10.2.jar
moreoverlays-1.21.3-mc1.19.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### List of all loaded packs

FreshAnimations_v1.7.zip
Nautilus3D_V1.7_[MC-1.13+].zip
Stay_True_1.19.zip
XeKr+redstone+display+1.20.zip
[1.19]+Clear+Water.zip

### Describe your issue

i added this res pack, and moved it up and down he list to get it to where i like,
its almost perfect.
it seems to overwrite the animations that are applied on my nether portal right now.
if i can get it to not do that it would be perfect.
any idea how i can do this?
[before adding the nautilus res pack](https://imgur.com/6TNPGNK)
[after adding the nautilus res pack](https://imgur.com/n9o6y8l)
[current location of the pack in the list](https://imgur.com/OkO7ih4)

**Comment by FabianMPunkt** [comment]
You can try this:
goto `\Nautilus3D - [1.13 +]\assets\minecraft\optifine\ctm`
and delete the folder `nether_portal`

please tell me if this did the trick!

**Comment by user4302** [comment]
that works :D

ohh, my bad, idk why i set is as that, ill update the version
