### ISSUE TITLE
Disable in the files?

### ISSUE THREAD

**Issue by rainysux** [FabianMPunkt/Nautilus3D#7]
Is there a way to disable the tree foilage for leaves? I personally think it doesnt fit for my barebones texturepack :>

**Comment by FabianMPunkt** [comment]
Hey, you can go into the packs folder and navigate to this dirrctory:
`assets/minecraft/blockstates/`
In there just search "leave" and these files. This way the game doesn't know that the leaves even exist.

If there are still problems goto:
`assets/minecraft/models/block/`
And delete the folder called 'leaves'

**Comment by labitore** [comment]
all leaves turn black and purple when it ry to delete the leaves folder
