### ISSUE TITLE
Doors reference "door_bottom.json" as parent which no longer exists, causing critical bugs

### ISSUE THREAD

**Issue by TBlazeWarriorT** [FabianMPunkt/Nautilus3D#9]
### Game Version

1.20.1

### List all installed mods

(Forge)BedrockPlusMod-1.19.x-1.20.x-1.1.2.jar
3dskinlayers-forge-1.5.4-mc1.20.1.jar
aether-1.20.1-1.0.0-beta.1.4-neoforge.jar
alexscaves-1.0.8.jar
alexsmobs-1.22.6.jar
appleskin-forge-mc1.20.1-2.5.1.jar
aquamirae-6.API15.jar
AttributeFix-Forge-1.20.1-21.0.3.jar
auto_third_person-forge-1.20.1-2.1.jar
AxesAreWeapons-1.7.2-forge-1.20.2.jar
betterfpsdist-1.20.1-4.0.jar
BetterTridents-v8.0.1-1.20.1-Forge.jar
Bookshelf-Forge-1.20.1-20.1.6.jar
BorderlessWindow-1.20-1.6.0.jar
callablehorses-1.20.1-1.3.0.1c.jar
canary-mc1.20.1-0.2.7.jar
citadel-2.4.9-1.20.1.jar
citresewn-1.20.1-5.jar
ClearDespawn-forge-1.20.1-1.1.13.jar
cloth-config-11.1.106-forge.jar
collective-1.20.1-7.16.jar
Companion-1.20.1-forge-5.0.1.jar
configurabledespawntimer-1.20.1-3.2.jar
corpse-1.20.1-1.0.5.jar
CraftTweaker-forge-1.20.1-14.0.26.jar
create-1.20.1-0.5.1.f.jar
createaddition-1.20.1-1.1.1.jar
cristellib-1.1.3-forge.jar
ctov-3.3.6.jar
cupboard-1.20.1-2.1.jar
DeathFinder-v8.0.1-1.20.1-Forge.jar
deeperdarker-forge-1.20.1-1.2.1.jar
domesticationinnovation-1.7.1-1.20.1.jar
DungeonsArise-1.20.1-2.1.57-release.jar
EasyAnvils-v8.0.1-1.20.1-Forge.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
easy_mob_farm_1.20.1-7.0.0.jar
embeddium-0.2.13+mc1.20.1.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.9.jar
ender_chested-1.20.1-1.1.0.jar
entityculling-forge-1.6.2-mc1.20.1.jar
entity_model_features_forge_1.20.1-1.1.0.jar
entity_texture_features_forge_1.20.1-4.6.1.jar
Fallingleaves-1.20.1-2.1.0.jar
FarmersDelight-1.20.1-1.2.3.jar
FastLeafDecay-31.jar
ferritecore-6.0.1-forge.jar
files.txt
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
FpsReducer2-forge-1.20-2.5.jar
friendsandfoes-forge-mc1.20.1-2.0.2.jar
geckolib-forge-1.20.1-4.2.4.jar
horsestonks-forge-1.17+-1.0.1.jar
ImmediatelyFast-1.2.7+1.20.2.jar
immersive_armors-1.6.1+1.20.1-forge.jar
Incendium_1.20.2_v5.3.3.jar
InventoryProfilesNext-forge-1.20-1.10.9.jar
inventorytotem-1.20.1-3.1.jar
ironchests-5.0.2-forge.jar
Jade-1.20.1-forge-11.6.3.jar
jei-1.20.1-forge-15.2.0.27.jar
JeiTweaker-forge-1.20.1-8.0.6.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
justzoom_forge_1.0.2_MC_1.20.1.jar
Keep Command History-1.0.2+1.20.1-forge-1.0.2.jar
konkrete_forge_1.6.1-2_MC_1.20.jar
kotlinforforge-4.5.0-all.jar
libIPN-forge-1.20-4.0.0.jar
L_Enders_Cataclysm-1.39+-1.20.1.jar
memoryleakfix-forge-1.17+-1.1.2.jar
modelfix-1.14.jar
modernfix-forge-5.9.3+mc1.20.1.jar
Modifiers-forge-1.20.1-0.1.3.jar
multimine-1.20.1.2.jar
naturalist-forge-4.0.3-1.20.1.jar
notenoughanimations-forge-1.6.4-mc1.20.jar
Obscure-Tooltips-2.2.jar
obscure_api-15.jar
oculus-mc1.20.1-1.6.13.jar
PuzzlesLib-v8.1.9-1.20.1-Forge.jar
ResourcePackOverrides-v8.0.2-1.20.1-Forge.jar
RespawningAnimals-v8.1.1-1.20.1-Forge.jar
saturn-mc1.20.1-0.0.7.jar
sculkhorde-1.20.1-0.7.15.jar
servercore-forge-1.3.9+1.20.1.jar
simple_fps-1.20.X-1.3.0.jar
sliceanddice-forge-3.2.0.jar
smoothboot-mc1.20.1-0.0.3.jar
smoothchunk-1.20.1-3.5.jar
Stackable+Potions-forge-1.20.1-1.0.0.jar
starlight-1.1.2+forge.1cda73c.jar
StylishEffects-v8.0.0-1.20.1-Forge.jar
Terralith_1.20.2_v2.4.8.jar
ToolSwap-1.20.1-5.0.0.jar
Towns-and-Towers-1.11.1-Fabric+Forge.jar
TravelersBackpack-1.20.1-9.1.11.jar
UniversalBoneMeal-v8.0.1-1.20.1-Forge.jar
UniversalEnchants-v8.0.0-1.20.1-Forge.jar
villagernames-1.20.1-7.1.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
waveycapes-forge-1.4.0-mc1.20.jar
X-HP-1.20.1-1.0.3-SNAPSHOT.jar
XaerosWorldMap_1.37.1_Forge_1.20.jar
Xaeros_Minimap_23.9.1_Forge_1.20.jar
YungsApi-1.20-Forge-4.0.2.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.4.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar

### List of all loaded packs

BlazeLab
FA+Details-v1.0
FA+Objects-v1.0
Nautilus3D_V1.9_[MC-1.13+]
Particles+V.1.2.5
Spider-Edit-Edit
ZinkForFresh v1.00
§bRAY's§r+3D+Rails
astraliyte-s-animated-textures-1-3.zip
Fancy_Beds_V2.1-[1.19].zip
files.txt
FreshAnimations_v1.8.1.zip
Incendium_Optional_Resourcepack_1.20.1_v5.3.7.zip
NoZ-Fighting-v1.3.zip
Os' Amethyst Indicator.zip
Shield Corrections [Colored].zip
unique-spawn-eggs-v1-5.zip
xali's+Enchanted+Books+v0.12.0.zip
xali's+Potions+v1.0.zip
[1.4]+Enhanced+Boss+Bars.zip
§9Better3DLadder§7_1.1.zip

### Describe your issue

Several door files, such as crimson and warped doors, reference door_bottom.json, which no longer exists, as it was replaced by door_bottom_left and right. This not only causes a console error but can cause doors to go completely unsync until the map is reopened, being unable to open, close, break or replace them until the map is reopened. The issue seems to be fully triggered after I come back from the nether (so from another dimension).
Removing the parent reference or updating it to the 1.20 format seems to solve the issue.
I'm using the 1.20.1 version of the pack because Mojunk broke resource pack compatibility in 1.20.2.

**Comment by FabianMPunkt** [comment]
Hey, that's a lot of mods you have there xD
Could you possibly upload some screenshots, or even videos of the "unsync" issue? Ia have never seen anything like that.
And what Forge version are you on?
Does any of those mods or resource packs change something about the doors, besides Nautilus. Because otherwise, i'm not sure what would cause issuse like that..

**Comment by TBlazeWarriorT** [comment]
> Hey, that's a lot of mods you have there xD Could you possibly upload some screenshots, or even videos of the "unsync" issue? Ia have never seen anything like that. And what Forge version are you on? Does any of those mods or resource packs change something about the doors, besides Nautilus. Because otherwise, i'm not sure what would cause issuse like that..

I compared the resource pack directly against the vanilla jar, but for a second I forgot just my word sometimes isn't enough 🤣 
1.16.5 vanilla jar (compatible with the pack):
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/25572454/b6cd925f-4ea5-40d5-9f8f-033532924bb7)

1.20.1 vanilla jar (doesn't have the referenced json, will 100% trigger *some* error):
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/25572454/b0a47fcc-c437-4b6a-be8a-99c1acc05ca6)

Console error (logged by vanilla, not a mod):
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/25572454/037f888c-f059-4e47-8eb0-c18e6045a6b8)

The bug seems to be actually random and somewhat hard to trigger, so I don't have a screenshot for it, but it looked exactly like this:
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/25572454/82895fd4-c49a-4e9b-9ab4-a2075aa65fb4)
You can even disregard the "unsync" part of the bug report if you'd prefer and just go with the console error I've shown above, although I'm 100% certain they are both related to each other and the door issue is too specific not to be caused by this.

**Comment by FabianMPunkt** [comment]
Hmm this is very strange..
So the "door_bottom_left.json" etc.. files are actually templates for the default door models. Nautilus3D doesn't use these templates at all. All doors is Nautilus3D actually have a unique model with their own textures, so they aren't in relation to the default files at all.
For example: In the blockstates file [warped_door.json](https://github.com/FabianMPunkt/Nautilus3D/blob/main/Pack/Nautilus3D%20-%20%5B1.13%20%2B%5D/assets/minecraft/blockstates/warped_door.json):
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/78741736/7579099f-39fd-4788-9127-5f8f08e61e30)
It calls on the individual model files which are in another directory, compared to the default door models. The Nautilus3D doors have nothing to do with the default door models from your screenshots.

Furthermore, Resource packs load their assets based on the order of the packs on the list. The bottom-most pack loads first, then each pack placed above it replaces assets of the same name with its assets. This means, even if a resource pack doesn't conatin the "door_bottom.json" files, the default ones are still present. Just not being used.

I suspect that one of your installed mods or resource packs may alter the behaviour of doors somehow.
You could try copying the door files you mentioned into the Nautilus3D model folder..

**Comment by TBlazeWarriorT** [comment]
> Hmm this is very strange.. So the "door_bottom_left.json" etc.. files are actually templates for the default door models. Nautilus3D doesn't use these templates at all. All doors is Nautilus3D actually have a unique model with their own textures, so they aren't in relation to the default files at all. For example: In the blockstates file [warped_door.json](https://github.com/FabianMPunkt/Nautilus3D/blob/main/Pack/Nautilus3D%20-%20%5B1.13%20%2B%5D/assets/minecraft/blockstates/warped_door.json): ![image](https://private-user-images.githubusercontent.com/78741736/291992005-7579099f-39fd-4788-9127-5f8f08e61e30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMDA2ODYsIm5iZiI6MTcwMzEwMDM4NiwicGF0aCI6Ii83ODc0MTczNi8yOTE5OTIwMDUtNzU3OTA5OWYtMzlmZC00Nzg4LTkxMjctNWY4ZjA4ZTYxZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE5MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOTJkODY4ZjY4NWExMWE5ZWJhMmRmZTM1YjdmOWJiNDA3YWZmMjkwNGZhNmU4YTdkMzNmOGZiZDZhYzU5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBkY8suLBcSY0fVGZ74CJcqX9eI9V8HlX6HkWaW4GlQ) It calls on the individual model files which are in another directory, compared to the default door models. The Nautilus3D doors have nothing to do with the default door models from your screenshots.
> 
> Furthermore, Resource packs load their assets based on the order of the packs on the list. The bottom-most pack loads first, then each pack placed above it replaces assets of the same name with its assets. This means, even if a resource pack doesn't conatin the "door_bottom.json" files, the default ones are still present. Just not being used.
> 
> I suspect that one of your installed mods or resource packs may alter the behaviour of doors somehow. You could try copying the door files you mentioned into the Nautilus3D model folder..

Your pack does reference door_bottom.json (deprecated by Minecraft), and can be seen here, on this github
https://github.com/FabianMPunkt/Nautilus3D/blob/main/Pack/Nautilus3D%20-%20%5B1.13%20%2B%5D/assets/minecraft/models/block/doors/doors/crimson/crimson_door_bottom.json
You can see `	"parent": "minecraft:block/door_bottom",` at line 4 and I believe this should be updated or removed on all door files containing it, which was actually my original goal with this bug report.

**Comment by FabianMPunkt** [comment]
Holy shit good catch! That is definitely not supposed to be there xD
I noticed a few other instances of this in the past with a few other models. I must have missed a few. I'll have a look through all the files and remove each false reference. The changes will be in the next major update. In the meantime you can just delete them on your end if you find any.

**Comment by FabianMPunkt** [comment]
I now removed all parent-references on models containing other elements, and i added the missing display-data:
https://github.com/FabianMPunkt/Nautilus3D/commit/a5d8c4fbf05bd3260479678a8a4796ce79888844

**Comment by TBlazeWarriorT** [comment]
> Holy shit good catch! That is definitely not supposed to be there xD I noticed a few other instances of this in the past with a few other models. I must have missed a few. I'll have a look through all the files and remove each false reference. The changes will be in the next major update. In the meantime you can just delete them on your end if you find any.

Thank you for that
Turns out it indeed was not related to my door breaking (but I still have no idea what causes it), but I'm glad it got fixed and that still fixes the console spam
